### ISSUE TITLE
writing IFF files?

### ISSUE THREAD

**Issue by rcoenen** [wiesmann/ilbm.js#5]
any idea how this can be changed to also write IFF?

**Comment by wiesmann** [comment]
Well, you would need one or more encoders, and then write the data inside an IFF container.
Writing RGB iff would be reasonably easy, but the files would be huge. 
What would be expected input, what would be the expected IFF variant?

**Comment by wiesmann** [comment]
There is a online version of Deluxepaint which is able to write IFF files. 

https://github.com/steffest/DPaint-js

**Comment by rcoenen** [comment]
thats amazing... an Amiga Dpaint clone in the browser with IFF / ILBM writing capabilities
